import React, { useState } from 'react';
import { Download, FileText, Calendar, Filter, Search } from 'lucide-react';
import { usePhoto } from '../context/PhotoContext';

export function Reports() {
  const { claims } = usePhoto();
  const [selectedClaim, setSelectedClaim] = useState<string>('');

  const completedClaims = claims.filter(claim => claim.status === 'completed');

  const generateReport = (claimId: string) => {
    const claim = claims.find(c => c.id === claimId);
    if (!claim) return;

    // Simulate report generation
    const reportData = {
      claimName: claim.name,
      dateGenerated: new Date().toLocaleDateString(),
      totalPhotos: claim.photos.length,
      includedPhotos: claim.photos.filter(p => p.reportIncluded).length,
      duplicatesFound: claim.photos.filter(p => p.isDuplicate).length,
      lowQualityPhotos: claim.photos.filter(p => p.qualityScore < 70).length,
      damageTypes: [...new Set(claim.photos.map(p => p.damageType).filter(Boolean))],
      locations: [...new Set(claim.photos.map(p => p.location).filter(Boolean))]
    };

    // Create downloadable report
    const reportContent = `
CLAIMSNAP DAMAGE ASSESSMENT REPORT
=====================================

Claim: ${reportData.claimName}
Date Generated: ${reportData.dateGenerated}

SUMMARY
-------
Total Photos Uploaded: ${reportData.totalPhotos}
Photos Included in Report: ${reportData.includedPhotos}
Duplicates Identified: ${reportData.duplicatesFound}
Low Quality Photos: ${reportData.lowQualityPhotos}

DAMAGE TYPES IDENTIFIED
-----------------------
${reportData.damageTypes.join('\n')}

LOCATIONS DOCUMENTED
--------------------
${reportData.locations.join('\n')}

PHOTO INVENTORY
---------------
${claim.photos.filter(p => p.reportIncluded).map((photo, index) => 
  `${index + 1}. ${photo.file.name}
     Damage Type: ${photo.damageType}
     Location: ${photo.location}
     Quality Score: ${photo.qualityScore}%
     Tags: ${photo.tags.join(', ')}`
).join('\n\n')}

Generated by ClaimSnap - Insurance Photo Organization System
`;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${claim.name.replace(/[^a-z0-9]/gi, '_')}_report.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex-1 p-6">
      {/* Header */}
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-text-primary mb-2">Reports</h1>
        <p className="text-text-secondary">Generate and download claim reports</p>
      </div>

      {/* Filters */}
      <div className="card mb-6">
        <div className="flex flex-col md:flex-row gap-4">
          <div className="flex-1">
            <label className="block text-sm font-medium text-text-primary mb-1">Search Claims</label>
            <div className="relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400" />
              <input
                type="text"
                placeholder="Search by claim name..."
                className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-primary"
              />
            </div>
          </div>
          <div className="md:w-48">
            <label className="block text-sm font-medium text-text-primary mb-1">Date Range</label>
            <button className="w-full flex items-center gap-2 px-3 py-2 border border-gray-300 rounded-md hover:bg-gray-50">
              <Calendar className="w-4 h-4" />
              Last 30 days
            </button>
          </div>
          <div className="md:w-32">
            <label className="block text-sm font-medium text-text-primary mb-1">Status</label>
            <button className="w-full flex items-center gap-2 px-3 py-2 border border-gray-300 rounded-md hover:bg-gray-50">
              <Filter className="w-4 h-4" />
              Completed
            </button>
          </div>
        </div>
      </div>

      {/* Claims List */}
      <div className="card">
        <h3 className="text-lg font-bold text-text-primary mb-4">Available Reports</h3>
        
        {completedClaims.length > 0 ? (
          <div className="space-y-4">
            {completedClaims.map((claim) => (
              <div key={claim.id} className="flex items-center justify-between p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors">
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-2">
                    <FileText className="w-5 h-5 text-text-secondary" />
                    <h4 className="font-medium text-text-primary">{claim.name}</h4>
                    <span className="px-2 py-1 bg-green-100 text-green-800 text-xs rounded-full">
                      Completed
                    </span>
                  </div>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm text-text-secondary">
                    <div>
                      <span className="font-medium">Photos:</span> {claim.photos.length}
                    </div>
                    <div>
                      <span className="font-medium">Included:</span> {claim.photos.filter(p => p.reportIncluded).length}
                    </div>
                    <div>
                      <span className="font-medium">Duplicates:</span> {claim.photos.filter(p => p.isDuplicate).length}
                    </div>
                    <div>
                      <span className="font-medium">Date:</span> {claim.dateCreated.toLocaleDateString()}
                    </div>
                  </div>
                </div>
                <button
                  onClick={() => generateReport(claim.id)}
                  className="btn-primary flex items-center gap-2 ml-4"
                >
                  <Download className="w-4 h-4" />
                  Download Report
                </button>
              </div>
            ))}
          </div>
        ) : (
          <div className="text-center py-12">
            <FileText className="w-12 h-12 text-gray-300 mx-auto mb-3" />
            <h4 className="text-lg font-medium text-text-primary mb-2">No Reports Available</h4>
            <p className="text-text-secondary">Complete some claims to generate reports</p>
          </div>
        )}
      </div>
    </div>
  );
}